tecnickcom/TCPDF

include/tcpdf_images.php

Minor mod to main loop in _parsepng().
I encountered a PNG file, which I had just created dynamically with GD library, that had a zero byte IDAT block. According to pngcheck, this is OK (see output below). However, _parsepng() called TCPDF_STATIC::rfread() with a length of zero, which subsequently called fread() with a length of zero, which threw an error because it won't accept a length of zero.
A minor modification to the main loop in _parsepng() fixed this issue.
Output of pngcheck is below:
File: test.png (32873 bytes)
chunk IHDR at offset 0x0000c, length 13
1200 x 284 image, 24-bit RGB, non-interlaced
chunk IDAT at offset 0x00025, length 8192
zlib: deflated, 32K window, default compression
chunk IDAT at offset 0x02031, length 8192
chunk IDAT at offset 0x0403d, length 8192
chunk IDAT …

Minor mod to PNG parsing

---

composer.json

It seems `fonts/` shouldn't be autoloaded since there is no class or interface definition there. Removing it can help composer take less time to generate classmap. Besides that, a personal reason is I'm sort of implementing my own autoloading mechanism with parsing and these fonts files take really long time to parse. 
Thanks

Remove fonts from classmap

---

tcpdf.php

A bug occurs when trying to print a table inside a page that itself contains columns. The table cell borders are all printed starting from the leftmost horizontal position within the page column.
More specifically, this occurs when using MultiCell to print each table cell's text. Say that the page has  2 equal columns of width 80, and that we want to print text in a table with 4 columns of width 20 each (the widths of the table columns does not matter). The text of each table cell is printed using MultiCell. Each cell has a non-null border (say `B`). When the table gets printed, we'd expect the border of each cell to be printed from x position 0 to 20, 20 to 40, 40 to 60, 60 to 80 (these numbers refer to the horizontal positions relative to the left edge of the current page column). …

fixed border in multicell printing across columns

---

tcpdf.php

Previously, the right side padding on HTML cells was set to whatever the left side was (or right for RTL text), making it impossible to actually control the left and right padding independently on these elements.  This fixes that.

Handle side padding correctly on writeHTML

---

tools/tcpdf_addfont.php

PHP in different operating systems installed location is not the same, so can not write so.

Fix tcpdf_addfont.php Bug

---

tcpdf.php

Function write2DBarcode() have problem in 7.1.6, with this fix run in PHP 5 Upwards.
source:
http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.types

refactoring write2DBarcode() in tcpdf

---

include/barcodes/pdf417.php

getErrorCorrectionLevel throws a fatal ArithmeticError when a negative number is passed for the `$ecl` parameter. By reversing the order of operations in this function, this error can be easily avoided.
Here is the error log showing the specifics of the error:
```
[24-Jun-2017 23:54:12 Europe/Berlin] PHP Fatal error:  Uncaught ArithmeticError: Bit shift by negative number in /Applications/MAMP/htdocs/TCPDF/include/barcodes/pdf417.php:747
Stack trace:
#0 /Applications/MAMP/htdocs/TCPDF/include/barcodes/pdf417.php(589): PDF417->getErrorCorrectionLevel(-1, 14)
#1 /Applications/MAMP/htdocs/TCPDF/tcpdf_barcodes_2d.php(289): PDF417->__construct('http://www.tcpd...', -1, 2, Array)
#2 /Applications/MAMP/htdocs/TCPDF/tcpdf_barcodes_2d.php(69): TCPDF2DBarcode->setBarcode('http://www.tcpd...', …
```

Reverse order of operations in getErrorCorrectionLevel

---

tcpdf.php

Notice happens when using a numberless TOC and breaks local testing.

Fix for Notice -> Undefined index: F0

---

include/tcpdf_static.php

When `TCPDF_STATIC::fileGetContents` is called with a relative path while `$_SERVER['SCRIPT_URI']` is set, this method _always_ used the web-url to retrieve the contents. This fix will just add the url as one of the alternatives to be checked later in the method.

Add url as an alternative path instead of returning directly

---

CHANGELOG.TXT
tcpdf.php

It is to fix a pb on Chrome Pdf Viewer.
Lots of pdf lib have the pb : mpdf/mpdf#283
I know that now this package is deprecated, but since the new lib is not ready, it could be cool to manage bug fix on this version ;)

fix Undesired mouseover effect on links in PDF on Chrome Pdf Viewer

---

tcpdf.php

composer.json for TCPDF claims support for PHP 5.3 and short array syntax is not in this old version. This undos commit 865cd727fc29b080e8da1959566de5078a605c73 in char101:patch-1

Restore PHP 5.3 compatibility Verified 11f0fd3

---

tcpdf.php

The $size variable in the SetFontSize function is supposed to be a float type, but a string can be passed in like "14px" causing an error in PHP 7.  Re-casting the variable is a simple solution to fix the variable type if it was incorrectly passed in.

"Non well formed numeric value" error occurs in PHP 7

---

tcpdf.php

This PR fixes a security vulnerability that has been presented at this years Black Hat USA 2018 conference. The white paper is available here:
https://github.com/s-n-t/presentations/blob/master/us-18-Thomas-It's-A-PHP-Unserialization-Vulnerability-Jim-But-Not-As-We-Know-It-wp.pdf
The fix checks if the file path begins with a stream wrapper other than `http` and `https` and throws an exception if so.

Security fix for disclosed stream wrapper attack

---

tcpdf.php

Fix of issue with html tags inside RTL languages, space reversion shouldn't be performed on RTL strings. Consider next code:
$pdf->SetFont('dejavusans', '', 14, '', false);
$pdf->setRTL(true);
$htmlhebrew = "אנ <b>לא</b> ודעת";
$pdf->WriteHTML($htmlhebrew, true, 0, true, 0);
it will output
אנלאודעת
with missing spaces around bold text לא
Expected output is:
אנ לא ודעת
with spaces around bold text לא

Fix of issue with html tags inside RTL languages

---

tcpdf.php

Add IgnoreAnnotation annotations to ignore `@public`, `@protected`, `@pre` cause doctrine parser searching for imports and is throwing
`[Semantical Error] The annotation "@pre" in method TCPDF::getStringHeight() was never imported. Did you maybe forget to add a "use" statement for this annotation?
`

Add ignore Annotation annotation

---

tcpdf.php

BC break: no
In PHP7.3 there is an error when continue is used in switch. I was thinking about `continue 2`, but it may change logic of this method. Break is more safe.
PHP change: https://github.com/php/php-src/commit/04e3523b7d095341f65ed5e71a3cac82fca690e4
RFC: https://wiki.php.net/rfc/continue_on_switch_deprecation
(RFC is Withdrawn from PHP7.3 - instead of it warning is thrown - see PHP change).

Fix continue in switch for PHP7.3

---

tcpdf.php

The current implementation does not allow negative y values for the `MultiCell` method.
If you enter a negative y value, then the method `$this->SetY($y)` is called. It converts the negative y position to a positive position and sets `$this->y` correctly.
The method `MultiCell` however still uses the local `$y` which is still negative and this leads to errors.

Fixes MultiCell not working with negative y values

---

include/tcpdf_fonts.php

I had some cases where $currentfont['subsetchars'] was 0, which lead to fatal errors because of unsupported operand types. This is fixed by this change.

Fix unsupported operand types error when codepoints arrays are merged

---

include/tcpdf_static.php

Currently only the first path in the `$alt` array gets checked. This pull request fixes this so that all paths are checked.

Fix TCPDF_STATIC::fileGetContents()

---

tcpdf.php

Add an additional empty test to prevent error in PHP 7.2. Without this test, the variables might get initialized as an empty string, which will lead to an error during the following multiplication.
There might be more lines with this problem - these are the ones I found.

Update tcpdf.php to prevent errors in PHP 7.2

---

include/tcpdf_colors.php

As the spot color array contains the user defined spotcolors provided by AddColor() we need to use the original color name here (as stored in $hcolor) and not the flattened one.
Example for usage <span style="color:SPOTCOLOR 15/5;">Your text here</span>

[BUGFIX] fix SpotColor handling in HTML

---

tcpdf.php

related to #123
Solves the following warning in PHP 7.4 (beta4)
*Array and string offset access syntax with curly braces is deprecated*

don't use deprecated array syntax (PHP 7.4)

---

include/tcpdf_static.php

return value should also be checked for a non-empty string

file_get_contents

---

tcpdf.php

- PHP `7.4.0 alpha 1`
- TCPDF `6.2.26`
The constructor of `TCPDF` causes a warning in PHP 7.4 (currently still under dev). It's fine in 7.3 and former versions.
```
Warning: chr() expects parameter 1 to be int, string given in C:\Users\Clover\Desktop\test\php\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php on line 1671
```
https://github.com/tecnickcom/TCPDF/blob/756908329d3ebf553d069f0dfede7a81a8229a4e/include/tcpdf_fonts.php#L1666
https://github.com/tecnickcom/TCPDF/blob/756908329d3ebf553d069f0dfede7a81a8229a4e/include/tcpdf_fonts.php#L1803
https://github.com/tecnickcom/TCPDF/blob/756908329d3ebf553d069f0dfede7a81a8229a4e/include/tcpdf_fonts.php#L2099
https://github.com/tecnickcom/TCPDF/blob/756908329d3ebf553d069f0dfede7a81a8229a4e/tcpdf.php#L1963
I don't see a reason why it's called …

Fix a warning for PHP 7.4

---

tcpdf.php

Generating a PDF file with a hyperlink like "tel:12345" results in an error: "Errstr: Undefined index: path" due to the fact that parse_url should only be used for URL not URI. 
SOURCE: https://www.php.net/manual/en/function.parse-url.php
"This function is intended specifically for the purpose of parsing URLs and not URIs."
This fix does not prevent parsing the link but checks if the parsed result contains a 'path'. If it does not than the rest of the if statement is ignored and no error is generated.

URI in PDF can result in E_NOTICE

---

tcpdf.php

I noted a performance issue using TCPDF when doing a lot of clones of the instance, it's caused by the destructor being called multiple times to cleanup things that already have been cleaned
This checks if the files have already been cleaned before redoing an expensive filesystem operation again (glob)

Fix performance issue of cloned instances

---

tcpdf.php

```
*** PHP Notice(8): Undefined property: GLPIPDF::$imagekeys
*** PHP Warning(2): Invalid argument supplied for foreach()
```
P.S. GLPIPDF is a simple class extending TCDPF
https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/glpipdf.class.php#L42

fix Undefined property: GLPIPDF::$imagekeys

---

include/barcodes/datamatrix.php

Resolved deprecation error in datamatrix.php: "Deprecated: Array and string offset access syntax with curly braces is deprecated"

Fixed datamatrix.php for PHP 7.4

---

tcpdf.php

PHP 7.3 casts integers to strings.
PHP 7.4 throws the error `Trying to access array offset on value of type int`

PHP 7.4 - cannot use array offset on integers

---

tcpdf.php

added @ to prevent crash in case that we have no list access in the cache path

Prevent crash in case of no list access in cache path

---

tcpdf.php

Fix issue #176, a syntax error when accessing an index of a casted variable

Fix #176: syntax error on line 12387 (invalid usage of array index)

---

include/tcpdf_static.php

Only a small change to maintain PHP 5.3 compatibility.
PHP 5.3 is EOL for quite a long time, but still in use :(

Changed [] to array() to maintain PHP 5.3 compat.

---

include/tcpdf_fonts.php
include/tcpdf_static.php

Some deprecation errors are trigerred when exporting a PDF in PHP 8. If these errors are displayed, it prevents sending valid PDF headers/contents to the browser.
Even if these params are always set in internal use of fixed methods, I kept their optionnal state as they are declared in public methods.
```
PHP Deprecated function (8192): Required parameter $currentfont follows optional parameter $isunicode in ./vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php at line 1998
PHP Deprecated function (8192): Required parameter $currentfont follows optional parameter $isunicode in ./vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php at line 2024
PHP Deprecated function (8192): Required parameter $currentfont follows optional parameter $setbom in ./vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php at …
```

Fix optionnal parameters declaration (PHP8)

---

tcpdf.php

In PHP 7.4 passing empty $file string to Image() method results in following error:
"Trying to access array offset on value of type null" (line 6874, tcpdf.php).

Fix for PHP 7.4

---

tcpdf.php

Add the last flag to GetCharWidth().
This is because too much font space added when calculating the width.

Fix font_space

---

include/tcpdf_static.php

In `include/tcpdf_static.php` file, there are couple Curl calls that could use some additional Curl hardening.
1. Limit the maximum number of redirects Curl is allowed to follow. Currently, it is configured in PHP source code to 20. However, as a [security precaution, limit it to 5](https://php.watch/articles/php-curl-security-hardening#infinite-redirects).
2. Curl is used here for HTTP, HTTPS, and in one instance, for FTP URLs. With `CURLOPT_FOLLOWLOCATION` option enabled, this allows a malicious remote server to perform SSRF attacks and utilize all protocols Curl supports, such as LDAP, FTP, etc that are highly undesired. Setting a restricted [`CURLOPT_PROTOCOLS` value mitigates this vulnerability](https://php.watch/articles/php-curl-security-hardening#ssrf). In older Curl versions, it …

Curl Security: Limit protocols and redirects

---

tcpdf.php

This prevents the cloned object from removing temporary files
owned by the original object during cleanup, potentially
leaving some that were created during the transaction,
but these should be cleaned with the original object
Reopenining against the `main` branch as the `master` was abandoned and previous PR (#206) was closed without any comment.
Fixes #205

Remove file_id from the cloned object before destruction

---

tcpdf.php

I'm not sure if this is useful for the library outside of my project scope, but I noticed a lot of outgoing calls for the same files (we're generating printable PDF's).
I tried to minimize calls by saving file content to memory and checking if an image already exists in the image buffer.
Switching an if statement around, makes sure we check memory *before* we try to find the same info *again*.

Fix duplicate file retrieval

---

tcpdf.php

The use and internal explicit set of the `mb_internal_encoding` in TCPDF constructor may cause a lot of problems, when you deal with`mb_*` functions in your project, when you generating files with `TCPDF`.
For example: You probably have set something like this `mb_internal_encoding('utf-8')` in your project. As soon as you `new TCPDF()`, your code that uses `mb_*` may break until TCPDF instance is destroyed.
In my case, this caused a lot of `mb_substr()` function to stop working, which further resulted in broken PDF's.
I took the time to invest why this has been set in the constructor. In fact: There is no reason that this mb_internal_encoding override exist. All `mb_*` that are used inside TCPDF are always setting explicit encodings in the function call. So `mb_internal_encoding` is not …

removed mb_internal_encoding as it is useless

---

tcpdf.php

SVG path allows little values (<1) to follow-up without separator, like into this code :
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 674 133" width="674" height="133">
<path d="M118,133H91.6c8.79-2.37,19.45-5.51,21.35-6.46,7.06-3.53,8.68-7.41,8.68-20.78,0-.15.06-3.91,0-18.77" style="fill:#04b497"/>
</svg>
```
This part of the path is not well interpreted by the SVGPath() function : `-.15.06`
- should equiv `-.15 .06`
- is treated as `-.15`. The next value `.06` is ignored and the number are shifted and everything goes wrong
Some svg files may encouter this issue. You can get a full svg example file here :
http://next.pillot.fr/compact-svg-logo.svg
It looks well into the browser, but is ruined by tcpdf.
This commit is a proposal that solves the problem adding a space …

FIX SVGPath should accept 1.19.30 (equiv 1.19,.30) compacted values list

---

tcpdf.php

Fixes ""Warning: xml_parser_free(): supplied resource is not a valid XML Parser resource" when using SVG's containing other SVG's. Because parser was global, it's reference was being overwritten and couldn't be freed anymore.
I also added an explicit unset for the parser, as it is recommended by php.net to avoid memory leaks since PHP 7.0.0.0

Make sure parser follows the correct scope and gets unset

---

tcpdf.php

Fix issue #267
Optimized regular expressions, which fixed a bug with large HTML
Test code:
```php
<?php
require_once __DIR__ . './vendor/tecnickcom/tcpdf/tcpdf.php';
$html = file_get_contents('./test.html');
$pdf = new TCPDF('L', PDF_UNIT, 'A2', true, 'UTF-8', false);
$pdf->AddPage();
$pdf->SetFont('helvetica', null, 12);
// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');
$pdf->Output('example.pdf', 'I');
```
test.html in zip archive:
[test.html.zip](https://github.com/tecnickcom/TCPDF/files/5123493/test.html.zip)

Fix #267 -  Empty result for big reports with writeHTML()

---

include/tcpdf_static.php

Consider this bit of HTML:
```html
<ol type="i">
<li value="50000">this is a (small) bomb</li>
</ol>
```
Web browsers are don't display roman numerals above 3999, but TCPDF does, so `intToRoman(50000)` will return `mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm`.
This is not so bad with `50000` (only 50 bytes), but one of our clients had a `<li>` with a value attribute of more than 32000000000 in a similar (and apparently unintentional) bit of HTML that was passed to `writeHTMLCell()`, resulting in a memory allocation error.
According to the English language Wikipedia as it stands at the time of this PR (https://en.wikipedia.org/wiki/Roman_numerals#Standard_form), 3999 is the largest number that can be represented in the standard form of roman numerals.
Since this is my very first …

Fix vulnerability to roman numeral bombs

---

tcpdf.php

When creating PNG files, temporary file are not removed (search for __tcpdf_* in your temp directory). After this changes temp directory never has temporary files created by tcpdf

temporary files never deleted

---

tcpdf.php

When running a Symfony command that uses tcpdf.php, the process always returns with exit code 255. The check for `file_exists()` prevents that.
For some reason, the file is being deleted just a few lines before, see here:
```
if ($handle = @opendir(K_PATH_CACHE)) {
while ( false !== ( $file_name = readdir( $handle ) ) ) {
if (strpos($file_name, '__tcpdf_'.$this->file_id.'_') === 0) {
unlink(K_PATH_CACHE.$file_name); // file is deleted here
}
}
closedir($handle);
}
if (isset($this->imagekeys)) {
foreach($this->imagekeys as $file) {
if (strpos($file, K_PATH_CACHE) === 0) {
@unlink($file); // error is silenced, but still exit code 255 is the result
}
}
}
```
I added a simple `file_exists()` to prevent this from happening.

check if file exists before calling unlink

---

include/tcpdf_images.php

When an URL is given with query params, TCPDF is unable to determine it's extension. It will assume the entire string after "." is the extension.
I combined parse_url with path_info to retrieve the extenstion directly, if availabe.

Fix image file type for urls with query params

---

.gitattributes
.github/workflows/lint-docs.yml
.github/workflows/tests.yml
examples/barcodes/tcpdf_barcodes_1d_include.php
examples/barcodes/tcpdf_barcodes_2d_include.php
scripts/doctum.php
tests/.gitignore
tests/coverage.php
tests/launch.sh

This adds running all examples and generating coverage.
Also adds Doctum to parse phpdocs (it can also build docs: https://warnockpdf.long-term.support/api-docs/)
Results:
- CI: https://github.com/williamdes/TCPDF/actions/runs/696006109
- DOCS: https://github.com/williamdes/TCPDF/actions/workflows/lint-docs.yml
Coverage results example: https://codecov.io/gh/code-lts/WarnockPDF/tree/c8f6203e03fd91af6c74b5254c512e6f2df7ca0d

Add a CI for docs and running examples + (generating coverage !!)

---

tcpdf.php

with php8 functionality of following code has changed:  0 != 'text'.

fix color being filled to type 0 with php8

---

tcpdf.php

Under PHP8, this generated warnings. If a tag is not set, it would throw a warning. Because the downstream usage of the $lineStyle can handle undefined entries, it's safe to leave them unset here.

fix warnings for undefined tags for $lineStyle

---

.gitignore
examples/example_066.php
tests/launch.sh

```
composer dump-autoload
php -f examples/example_066.php > example_066.pdf
```
And then view the PDF with your browser

Add a new example with composer & fix CI

---

tcpdf.php

Fixes PHP 8.1 deprecation notice: Implicit conversion from float to int loses precision.
- [PHP RFC: Deprecate implicit non-integer-compatible float to int conversions](https://wiki.php.net/rfc/implicit-float-int-deprecate).
- https://github.com/phpmyadmin/phpmyadmin/runs/2806644704#step:10:35
```
PHP Deprecated:  Implicit conversion from float 1.1768666666666663 to int loses precision in /home/runner/work/phpmyadmin/phpmyadmin/vendor/tecnickcom/tcpdf/tcpdf.php on line 4179
PHP Deprecated:  Implicit conversion from float 1.1768666666666663 to int loses precision in /home/runner/work/phpmyadmin/phpmyadmin/vendor/tecnickcom/tcpdf/tcpdf.php on line 4180
```

PHP 8.1: Fix implicit conversion from float to int

---

tcpdf.php

When using text-transform: uppercase, convert "&NBSP;" back to lowercase "&nbsp;" so that it is recognized as a space by Adobe Acrobat rather than printing out "&NBSP;"

Leave &NBSP; lowercase when using text-transform

---

tcpdf.php

Changed from `int` to `float`, I've also added some related type declaration info.
It is initialized to `1.25`
https://github.com/tecnickcom/TCPDF/blob/456b794f1fae9aee5c151a1ee515aae2aaa619a3/examples/config/tcpdf_config_alt.php#L192

Fix cell_height_ratio type

---

tcpdf.php

#459 
```
[2021-12-20T11:15:04.984791+00:00] php.INFO: Deprecated: Implicit conversion from float 0.5820629629409302 to int loses precision {"exception":"[object] (ErrorException(code: 0): Deprecated: Implicit conversion from float 0.5820629629409302 to int loses precision at /var/www/svm/vendor/tecnickcom/tcpdf/tcpdf.php:7360)"} []
```

[php 8.1] fix deprecation notice for imagesetpixel

---

include/tcpdf_static.php

This patch fixes generating of AES128 (mode=2) encrypted PDF files, if the OpenSSL extension is available.
If OpenSSL available TCPDF used aes-256-cbc regardless if mode=2 oder mode=3 was selected - which resulted in an unusable PDF file.
Now the functions _AES and _AESnopad use aes-128-cbc or aes-256-cbc depending on the key size.

Fix AES128 encryption if the OpenSSL extension is installed

---

include/tcpdf_static.php
tcpdf.php

Hi @nicolaasuni , since the PR: https://github.com/tecnickcom/TCPDF/pull/345 by @williamdes 
There was a lot of phpdoc like this:
```
/**
* @param float $x
* @param float $y
**/
public function foo($x = '', $y = '')
```
So if you need to pass the `$y` value, you use `foo('', 42)`.
When using some static analysis tool, the `''` is reported as incorrect since the phpdoc expect a float.
Instead of changing the phpdoc to `float|string`, I preferred to change to `float|null` to not allow every string values.
And in order to be BC, I changed the check `=== ''` to use `TCPDF_STATIC::empty_string` method, which also check for null values.
I also found some others errors in the phpdoc, so I fixed them.

Fix phpdoc and prefer null as default value

---

tcpdf.php

Hello.
Fix for #411 
I did not change the current conditions, just turned off the setting of the Statе and StateModel parameters for text annotations, if they are not explicitly specified.
According to PDF specification 1.7, these parameters are optional.

fix text-annotation state options

---

include/tcpdf_static.php

A resource, not a string expected for param `$f`

Fix type hint for \TCPDF_STATIC::_freadint

---

.gitattributes
composer.json

Examples are embed in dist packages fetched from packagist. In such context, I guess they are not really usefull. Removing them will reduce the package weight from 1.8MB. As package is installed about 35 000 times a day, it will save lots of network trafic and disk space.

Remove examples from dist package

---

tools/.htaccess

Update the .htaccess files to support Apache 2.4 directives with backwards compatibility for Apache 2.2.
See: https://httpd.apache.org/docs/2.4/upgrading.html#run-time

Support Apache 2.4 directives in .htaccess file

---

examples/example_067.php
examples/index.php
tcpdf.php

This is, in particular, a problem for PhpSpreadsheet. See https://github.com/PHPOffice/PhpSpreadsheet/issues/1164. TCPDF thinks that there can be 0, 1, 2, or 3 components to shorthand border style, but there can be more, e.g. !important. Logic is rearranged to allow for more than 3. A new example file is added to demonstrate that the fix works correctly.

GetCssBorderStyle Has Problem When !important Is Specified

---

tcpdf.php

The updated places that used `AcceptPageBreak` assumed that a page break was added and increased X by the margin.  However, if the break wasn't added, it would put the text further to the right to the point that the width because so small or negative and no characters fit, causing an infinite loop.
```php
<?php
require_once('tcpdf_include.php');
class MYPDF extends TCPDF
{
public function crash()
{
$width = 140;
$val = '';
for ($i = 1; $i <= 100; $i++)
$val .= "Line $i\n";
$this->MultiCell($width, 10, $val, 1, 'L');
}
}
$pdf = new MYPDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->setMargins(10, 10, 10);
$pdf->setCellMargins(10, 0, 10, 0);
$pdf->setAutoPageBreak(false);
$pdf->setFont('helvetica', '', 12);
$pdf->AddPage();
$pdf->crash();
$pdf->Output('file.pdf', 'I');
```

Fix Infinite Loop in Multicell with Auto Page Breaks Off

---

tcpdf.php

Fixes PHP 8.1 deprecation warning in case null value given for Output:
```preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated```

Fixed: null check on Output($name) for PHP 8.1

---

tcpdf.php

When inserting HTML into the PDF using `writeHTML()`, if an element in the DOM has style "display:none" and there are no other elements after it, undefined offset errors occur.
Simple test script:
```php
<?php
require_once('tcpdf/tcpdf.php');
$pdf = new TCPDF();
$pdf->AddPage();
$html = '<p style="display:none">Foobar</p>';
$pdf->writeHTML($html);
$pdf->Output('/tmp/test.pdf', 'F');
exit;
?>
```
Expected behaviour: no errors.
Actual behaviour:
```
PHP Notice:  Undefined offset: 4 in /home/indrek/tcpdf/tcpdf.php on line 17362
PHP Notice:  Undefined offset: 4 in /home/indrek/tcpdf/tcpdf.php on line 17376
PHP Notice:  Undefined offset: 4 in /home/indrek/tcpdf/tcpdf.php on line 17427
PHP Notice:  Undefined offset: 4 in /home/indrek/tcpdf/tcpdf.php on line 17479
PHP Notice:  Undefined offset: …
```

Undefined offset error in writeHTML() when last DOM element has display:none

---

include/tcpdf_static.php

In order to take into account the port in the URLs (related to PR #148).

encodeUrlQuery takes into account the port

---

tcpdf.php

If $style is empty, PHP is throwing a warning.You need to set the default as empty string if $style is not set.

Fix for PHP 8.1

---

composer.json

As LICENSE.TXT states:  
> either version 3 of the License, or (at your option) any later version.

 Fix SPDX license ID

---

tcpdf.php

Fix found by @BrainforgeUK in Issue #564 
Tested and confirmed working in PHP 7.4 and PHP 8.2 by @kosmro

Fix #564 - Array offset error in PHP 7+

---

include/barcodes/qrcode.php

Fix of Deprecation warning with php 8.1 #614
Array key was expecting integer but float was being passed. Typecasting to int should fix this issue

Fix of Deprecation warning with php 8.1 #614

---

include/tcpdf_fonts.php

Fixes "use of "self" in callables is deprecated" warning is arising from tcpdf_fonts.php when using PHP >= 8.2

Fixes for PHP 8.2 in tcpdf_fonts.php - fixes #632

---

tcpdf.php

fix for #583

---

tcpdf_barcodes_1d.php

Using your S25 barcode generator I found a problem. The representation of the digit 8 was the same as 0. I fixed it. Now it is recognized correctly.
Additionally you were using different bar widths for the start and stop values. I changed this too.
One thing I did not change till now is the part where you add an leading 0 if the string is odd. Why do you do so? I can't find anything that S25 has to be even. Maybe you mixed it up with interleaved 2 of 5 bar code where you need the even number because the digits are represented from pairs of bars and whitespaces?

Fixed problems with S25 barcode

---

tcpdf.php

A small annotation fix with in line with PHPStan conditional returns types introduced in 1.6 
https://phpstan.org/blog/phpstan-1-6-0-with-conditional-return-types

Fix return type annotation

---

tcpdf.php

This PR just updates a couple of inconsistent type-hints in the phpdoc.
The header/footer margins are both `float`, but the getters/setters have  inconsistent PHPDOC.
`getFooterMargin()` has `@return float`, but `setFooterMargin()` has `@param int $fm`.
`getHeaderMargin()` has `@return float`, but `setHeaderMargin()` has `@param int $hm`.

Typehints for getHeaderMargin() and setHeaderMargin() are inconsistent

---

include/tcpdf_colors.php

Add possessive quantifiers to the regex to prevent catastrophic backtracking.
CVE-2024-22640
Fixes: #711

fix: CVE-2024-22640

---

tcpdf.php

This PR ensures that image link is converted only when it is really needed. This is FIX #770

Fixed image link for named internal destination

---

tcpdf.php

Fix for https://github.com/tecnickcom/TCPDF/issues/806

Wrong default value when $table_el['old_cell_padding'] is missing

---

include/tcpdf_colors.php
tcpdf.php

RGBA fills are incorrectly handled resulting in a 4 component array that ends up applied as a CMYK color.
This PR correctly converts the RGBA color to a 3 component (RGB) array. It also extracts the alpha component from the RGBA fill and applies it to the PDF objects CA component.

Fix for application of alpha component to SVG RGBA fills
