- tcpdf.php
Without this, you get an Illegal string offset warning.
> Set back link to empty array as initiated.

- tcpdf.php
Just avoiding: Notice  --> Uninitialized string offset: 0
> Check if the string is not empty

- tcpdf.php
See http://php.net/each. This function has been DEPRECATED as of PHP 7.2.0. Relying on this function is highly discouraged.
> Refactor deprecated each() calls to foreach()

- tcpdf.php
Credit to: https://github.com/spipu/TCPDF/commit/48e55aa595915da4fae55ea5f4c3e51203e866c4
> Fix Undesired mouseover effect on links

- tcpdf.php
pdfa_mode is false or the number version (1, 2 or 3)
Need it for factur-X generation (pdfa/3)
> Introduce other version of pdfA (2 and 3)

- tcpdf.php
> FIX - cast int pages to string

- tcpdf.php
PHP message: PHP Notice:  Trying to access array offset on value of type int in /vendor/tecnickcom/tcpdf/tcpdf.php on line 12385
> Fix php7.4 error

- tcpdf.php
Added an @ in front of unlink to avoid the crash.
> Prevents crash and files deletion.

- include/barcodes/pdf417.php
Just a PHP 7.4 fix seen in https://github.com/matomo-org/matomo/pull/15560
> fix curly braces in pdf417

- fonts/freefont-20100919/CREDITS
- fonts/freefont-20120503/CREDITS
> Fix EOL of text files

- include/barcodes/pdf417.php
- include/barcodes/qrcode.php
- include/tcpdf_colors.php
- include/tcpdf_fonts.php
- include/tcpdf_static.php
- tcpdf_barcodes_1d.php
PHP 8  "Required parameter follows optional parameter" deprecation fix
Some small other fixes
> General fixes and PHP 8 deprecation fixes

- tcpdf.php
Allows to pass some styles to `<hr>` tags
**Example:**
```html
<hr style="color: #ff0000; dash: 4">
```
**Render:**
> allow styles on <HR> tags

- tcpdf.php
> Fix docblock spelliong error

- tcpdf.php
> Update tcpdf.php version info

- include/tcpdf_static.php
> Increase internal version number to 6.4.1.

- composer.json
normalize CS using `ergebnis/composer-normalize`
> Normalize composer.json CS

- tcpdf.php
Allow PDF/A-2 documents support transparency as it PDF/A2 supports PDF/1.7 features, unlike PDF/A-1b
> Allows transparency in PDF/A-2 and PDF/A-3

- tcpdf.php
`U` modifier invert greediness which is hard to read, thus remove it
> Remove "U" modifier from regexes

- .github/workflows/tests.yml
- Run on PHP 8.1 normally
- Add nightly PHP as allowed to fail
> Run on PHP 8.1 normally and add nightly PHP as allowed to fail

- tests/launch.sh
While working on packaging tcpdf into Debian I did see that failing tests still did exit 0, so I added some debugging and fixed the errors
- https://salsa.debian.org/phpmyadmin-team/tcpdf/-/jobs/1831241#L765
- https://github.com/tecnickcom/TCPDF/runs/3115139236#step:9:151
> Fix failing tests and failing tests not marking exit code as 1

- tcpdf.php
@caufang has been fixing this manually in our project for years. (the space on 2973 was probably my IDE)
> fix - Named links have been broken. This fixes.

- tcpdf.php
Try it out at https://phpstan.org/r/06d9eec6-c5b6-4a24-a255-b59f91ebbb4e
> Footer and Header font phpdoc fixes + constructor $pdfa phpdoc fix + setHeaderData lw param fix

- tcpdf.php
> lowercase s in function names

- include/tcpdf_fonts.php
- tcpdf.php
This PR fixes some PHP 8.1 deprecations. I assume there are more occurences where the same deprecations are triggered, but those are the ones I encountered.
> fix: php 8.1 notices

- tcpdf.php
> Fix TypeError: count() in PHP8

- .github/workflows/tests.yml
- phpstan.neon.dist
https://github.com/phpstan/phpstan/issues/7955 was fixed
> Check fonts files with phpstan too
